[config]

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.ohmyposh]
input_path = '~/.config/matugen/templates/theme.omp.json'
output_path = '~/.config/ohmyposh/theme.omp.json'
